name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Set environments
        run: |
          {
            echo "version=v$(grep versionName app/build.gradle | awk '{print $2}' | tr -d \")"
            echo "commit=$(echo ${{ github.sha }} | cut -c -7)"
            echo "repo=$(echo ${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/})"
          } >> $GITHUB_ENV

      - name: Build with Gradle
        run: ./gradlew assembleDebug --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.repo }}(${{ env.version }}@${{ env.commit }})
          path: app/build/outputs/apk/debug/app-debug*.apk
